-- Table: users_linked_accounts

CREATE TABLE IF NOT EXISTS users_linked_accounts
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer NOT NULL,
    provider_name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    provider_id character varying(255) COLLATE pg_catalog."default" NOT NULL,
    linked_email character varying(255) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    raw_email json,
    CONSTRAINT users_linked_accounts_pkey PRIMARY KEY (id),
    CONSTRAINT unique_provider UNIQUE (provider_name, linked_email),
    CONSTRAINT fk_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)